//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdModelContainer : DbContext
    {
        public BdModelContainer()
            : base("name=BdModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Водители> ВодителиSet { get; set; }
        public virtual DbSet<Автомобили> АвтомобилиSet { get; set; }
        public virtual DbSet<Путевые_листы> Путевые_листыSet { get; set; }
    }
}
